[package]
name = "sixg-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sixg-common  = { path = "../6g-common" }
sixg-ntn     = { path = "../6g-ntn" }
sixg-semantic = { path = "../6g-semantic" }
thiserror.workspace = true
serde.workspace = true
tokio.workspace = true
